name: "build and deploy production"

on:
  push:
    tags:
      - "*"

jobs:
  build-production-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set nodejs version to 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - run: npm ci

      - name: Run build production
        run: npm run build

      - name: Upload dist folder artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-production
          path: dist
  deploy-to-production-job:
    needs: build-production-job
    runs-on: ubuntu-latest
    steps:
      - name: Download dist folder artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-production
          path: dist

      - run: ls dist

      - uses: actions/checkout@v4

      - name: publish react to github pages
        uses: bitovi/github-actions-react-to-github-pages@v1.2.2
