name: Github Actions Demo

on:
  push:
    branches:
      - main
  pull_request:
    # types:
    #   - opened
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build job"

  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - run: echo "Run job"

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - run: echo "Deploy job to production server"
